server:
  port: 8060

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/  #注册到服务器


feign:
  hystrix:
    enabled: true


management:
  server:
    port: 8068
  cloudfoundry:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
