server:
  port: 8010

spring:
  application:
    name: msg

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/  #注册到服务器



feign:
  hystrix:
    enabled: true





management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
